name: EO-Floods
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pydantic
  - jupyter
  - numpy=1.26.0
  - pandas=2.2.1
  - pip:
    - hydrafloods
    - geemap
    - pytest
    - pydantic_settings
    - mock
    - tabulate



