name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - tests/*
      - EO_Floods/*
      - pyproject.toml
  pull_request:
    branches:
      - main
    paths:
      - tests/*
      - EO_Floods/*
      - pyproject.toml


jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10','3.11']
    name: py ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true
    steps:

      - uses: actions/checkout@v3
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Setup env
        run: |
          mamba env create -f environment.yml
          mamba run -n EO-Floods pip install -e .
      - name: LOAD EE CREDENTIALS
        run: python ./.github/ee_token.py
        env:
          EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
      - name: Test
        run: |
          mamba run -n EO-Floods python -m pytest --verbose 



      